# Generated by Django 6.1.1 on 2026-09-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('dias', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('imagen', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('incluye', models.JSONField(default=list)),
                ('itinerario', models.JSONField(default=list)),
            ],
        ),
    ]
