# Generated by Django 6.1.1 on 2026-09-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='imagen',
            field=models.ImageField(upload_to='tours_images/'),
        ),
    ]
