# Generated by Django 6.1.1 on 2026-09-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
