# Generated by Django 6.1.1 on 2026-09-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_tour_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='categoria',
            field=models.CharField(choices=[('experiencia', 'Tour y Experiencias'), ('yate', 'Renta de Botes y Yates'), ('hotel', 'Hoteles'), ('transporte', 'Transportes'), ('internacional', 'Tours Internacionales'), ('a_medida', 'A Medida (Preguntar)')], default='experiencia', max_length=50),
        ),
        migrations.AddField(
            model_name='tour',
            name='es_popular',
            field=models.BooleanField(default=False),
        ),
    ]
