# Generated by Django 6.1.1 on 2026-10-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_tour_categoria_tour_es_popular'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerPromocional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(default='home_viaja_medida', max_length=100, unique=True)),
                ('imagen_desktop', models.ImageField(upload_to='banners_images/')),
                ('imagen_mobile', models.ImageField(blank=True, null=True, upload_to='banners_images/')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
