# Generated by Django 6.1.1 on 2026-10-04 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_bannerpromocional'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='destino_slug',
            field=models.CharField(choices=[('cartagena', 'Cartagena'), ('san_andres', 'San Andrés'), ('santa_marta', 'Santa Marta'), ('medellin', 'Medellín'), ('eje_cafetero', 'Eje Cafetero'), ('bogota', 'Bogotá'), ('tumaco', 'Tumaco'), ('cancun', 'Cancún (Internacional)'), ('punta_cana', 'Punta Cana (Internacional)'), ('madrid', 'Madrid (Internacional)')], default='cartagena', max_length=50),
        ),
        migrations.AddField(
            model_name='tour',
            name='region',
            field=models.CharField(choices=[('colombia', 'Colombia'), ('internacional', 'Internacional')], default='colombia', max_length=20),
        ),
    ]
