# Generated by Django 6.1.1 on 2026-10-04 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_tour_destino_slug_tour_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='categoria',
            field=models.CharField(choices=[('playas-islas', 'Playas & Islas'), ('hoteles-posadas', 'Hoteles & Posadas'), ('viajes-nacionales', 'Viajes nacionales'), ('viajes-internacionales', 'Viajes internacionales'), ('botes-privados', 'Botes & Privados'), ('planes-familias', 'Planes para familias'), ('experiencia', 'Tour y Experiencias'), ('yate', 'Renta de Botes y Yates'), ('hotel', 'Hoteles'), ('transporte', 'Transportes'), ('internacional', 'Tours Internacionales'), ('a_medida', 'A Medida (Preguntar)')], default='experiencia', max_length=50),
        ),
        migrations.AlterField(
            model_name='tour',
            name='destino_slug',
            field=models.CharField(choices=[('cartagena', 'Cartagena'), ('san_andres', 'San Andrés'), ('santa_marta', 'Santa Marta'), ('medellin', 'Medellín'), ('eje_cafetero', 'Eje Cafetero'), ('bogota', 'Bogotá'), ('cancun', 'Cancún (Internacional)'), ('madrid', 'Madrid (Internacional)')], default='cartagena', max_length=50),
        ),
    ]
