# Generated by Django 6.1.1 on 2026-10-05 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_alter_tour_categoria_alter_tour_destino_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='tours_galeria/')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='tours.tour')),
            ],
        ),
    ]
