# Generated by Django 6.1.1 on 2026-10-06 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_tourimagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='no_incluye',
            field=models.JSONField(default=list),
        ),
    ]
